import type { WorkspaceConfig } from './models.js';

export const DEFAULT_SHELF_CONFIG = {
  customerStages: [
    'Lead',
    'Early communication',
    'Materials/site',
    'Design/scheme',
    'Quotation negotiation',
    'Deal confirmation',
    'Delivery/installation',
    'Payment/after-sales',
    'Repurchase/referral/lost',
  ],
  customerSources: [
    'Walk-in inquiry',
    'Phone inquiry',
    'WeChat referral',
    'Old customer referral',
    'Local market visit',
    'Online platform',
    'Partner/designer referral',
  ],
  riskTags: [
    'Price-shopping/comparison',
    'Unclear demand',
    'Materials not cooperating',
    'Low budget',
    'Competitor price pressure',
    'Non-decision-maker',
    'Uncertain cycle',
    'High distance cost',
    'Payment risk',
    'Profit risk',
    'Long non-response',
    'Low trust',
  ],
  taskTypes: [
    'Follow-up',
    'Overdue follow-up',
    'Waiting for customer materials',
    'Waiting for design/scheme',
    'Scheme/quotation feedback confirmation',
    'Deposit collection',
    'Final payment collection',
    'Delivery/installation reminder',
  ],
  quotationFeeItems: [
    'Product amount',
    'Freight/shipping fee',
    'Installation fee',
    'Design/measurement/travel fee',
    'Discount amount',
    'Final quote total',
  ],
  fileTypes: [
    'Store/site photo',
    'Floor plan/dimensions',
    'Design/scheme file',
    'Quotation attachment',
    'Contract/order file',
    'Payment voucher',
    'Delivery/installation evidence',
  ],
  storeTypes: [
    'Convenience store',
    'Supermarket',
    'Community group-buying store',
    'Fresh food store',
    'Warehouse',
    'Pharmacy',
    'Mother/baby store',
    'Other retail',
  ],
  shelfProductCategories: [
    'Convenience-store shelf',
    'Supermarket shelf',
    'Warehouse rack',
    'Checkout counter',
    'Promotion display',
    'Fresh produce rack',
    'Beverage/wine shelf',
    'Storage accessories',
  ],
} as const;

export function createWorkspaceConfig(team_id: string, id = crypto.randomUUID()): WorkspaceConfig {
  return {
    id,
    team_id,
    customerStages: [...DEFAULT_SHELF_CONFIG.customerStages],
    customerSources: [...DEFAULT_SHELF_CONFIG.customerSources],
    riskTags: [...DEFAULT_SHELF_CONFIG.riskTags],
    taskTypes: [...DEFAULT_SHELF_CONFIG.taskTypes],
    quotationFeeItems: [...DEFAULT_SHELF_CONFIG.quotationFeeItems],
    fileTypes: [...DEFAULT_SHELF_CONFIG.fileTypes],
    storeTypes: [...DEFAULT_SHELF_CONFIG.storeTypes],
    shelfProductCategories: [...DEFAULT_SHELF_CONFIG.shelfProductCategories],
    createdAt: new Date().toISOString(),
  };
}
