import type { WorkspaceConfig } from './models.js';

export const DEFAULT_SHELF_CONFIG = {
  customerStages: [
    '线索',
    '初步沟通',
    '资料/现场',
    '设计/方案',
    '报价谈判',
    '成交确认',
    '交付/安装',
    '回款/售后',
    '复购/转介绍/流失',
  ],
  customerSources: [
    '到店咨询',
    '电话咨询',
    '微信转介绍',
    '老客户推荐',
    '本地市场拜访',
    '线上平台',
    '合作伙伴/设计师推荐',
  ],
  riskTags: [
    '比价/压价',
    '需求不清晰',
    '资料不配合',
    '预算偏低',
    '竞品价格压力',
    '非决策人',
    '周期不确定',
    '距离成本高',
    '回款风险',
    '利润风险',
    '长期未回复',
    '信任度低',
  ],
  taskTypes: [
    '跟进',
    '逾期跟进',
    '等待客户资料',
    '等待设计/方案',
    '方案/报价反馈确认',
    '定金催收',
    '尾款催收',
    '交付/安装提醒',
  ],
  quotationFeeItems: [
    '产品金额',
    '运输费',
    '安装费',
    '设计/测量/差旅费',
    '优惠金额',
    '最终报价合计',
  ],
  fileTypes: [
    '门店/现场照片',
    '平面图/尺寸资料',
    '设计/方案文件',
    '报价附件',
    '合同/订单文件',
    '付款凭证',
    '交付/安装凭证',
  ],
  storeTypes: [
    '便利店',
    '超市',
    '社区团购店',
    '生鲜店',
    '仓库',
    '药店',
    '母婴店',
    '其他零售',
  ],
  shelfProductCategories: [
    '便利店货架',
    '超市货架',
    '仓储货架',
    '收银台',
    '促销陈列架',
    '生鲜果蔬架',
    '饮料/酒水架',
    '仓储配件',
  ],
} as const;

export function createWorkspaceConfig(team_id: string, id = crypto.randomUUID()): WorkspaceConfig {
  return {
    id,
    team_id,
    customerStages: [...DEFAULT_SHELF_CONFIG.customerStages],
    customerSources: [...DEFAULT_SHELF_CONFIG.customerSources],
    riskTags: [...DEFAULT_SHELF_CONFIG.riskTags],
    taskTypes: [...DEFAULT_SHELF_CONFIG.taskTypes],
    quotationFeeItems: [...DEFAULT_SHELF_CONFIG.quotationFeeItems],
    fileTypes: [...DEFAULT_SHELF_CONFIG.fileTypes],
    storeTypes: [...DEFAULT_SHELF_CONFIG.storeTypes],
    shelfProductCategories: [...DEFAULT_SHELF_CONFIG.shelfProductCategories],
    createdAt: new Date().toISOString(),
  };
}
