import type { CreateQuotationInput, CreateTaskInput, Quotation, QuotationLineItem, QuotationSet, SalesTask, SessionContext } from '../domain/models.js';
import { getCustomer } from './customers.js';
import { getDefaultOpportunity, getOpportunity } from './opportunities.js';

const STORAGE_KEY='shelf-crm-mvp-flow-state-v1'; const ORDER_STORAGE_KEY='shelf-crm-order-flow-state-v1';
interface State{tasks:SalesTask[];quotations:Quotation[];quotationSets:QuotationSet[]}
const emptyState=():State=>({tasks:[],quotations:[],quotationSets:[]});
const now=()=>new Date().toISOString();
const createId=()=>globalThis.crypto?.randomUUID?globalThis.crypto.randomUUID():`manual-${Date.now()}-${Math.random().toString(16).slice(2)}`;
function money(value:unknown):number{const n=Number(value??0);return Number.isFinite(n)?Math.max(0,Math.round(n*100)/100):0}
function dayOffset(days:number):string{const d=new Date();d.setDate(d.getDate()+days);return d.toISOString().slice(0,10)}
function rawState():State{if(typeof localStorage==='undefined')return emptyState();const raw=localStorage.getItem(STORAGE_KEY);return raw?{...emptyState(),...JSON.parse(raw)}:emptyState()}
function saveState(state:State):void{localStorage.setItem(STORAGE_KEY,JSON.stringify(state))}
function normalizeState(session?:SessionContext):State{
  const state=rawState();let changed=false;
  for(const quotation of state.quotations){
    if(!quotation.quotationSetId){const set:QuotationSet={id:createId(),team_id:quotation.team_id,customerId:quotation.customerId,opportunityId:quotation.opportunityId??'',name:'历史报价',createdAt:quotation.createdAt};state.quotationSets.push(set);quotation.quotationSetId=set.id;changed=true}
    if(!quotation.updatedAt){quotation.updatedAt=quotation.createdAt;changed=true}
  }
  if(changed&&typeof localStorage!=='undefined')saveState(state);return state;
}
function customerError(session:SessionContext,customerId:string){return getCustomer(session,customerId)?undefined:'客户不存在或不属于当前团队。'}
function resolveOpportunity(session:SessionContext,customerId:string,opportunityId?:string){const o=opportunityId?getOpportunity(session,opportunityId):getDefaultOpportunity(session,customerId);return o?.customerId===customerId?o:undefined}

export function listTasks(session:SessionContext):SalesTask[]{return normalizeState().tasks.filter(t=>t.team_id===session.currentTeam.id).sort((a,b)=>a.status.localeCompare(b.status)||a.dueAt.localeCompare(b.dueAt))}
export function createTask(session:SessionContext,input:CreateTaskInput):{task?:SalesTask;error?:string}{const error=customerError(session,input.customerId);if(error)return{error};const opportunity=resolveOpportunity(session,input.customerId,input.opportunityId);if(!opportunity)return{error:'项目不存在或不属于当前客户。'};const title=input.title.trim();if(!title)return{error:'请填写任务标题。'};const state=normalizeState();const task:SalesTask={id:createId(),team_id:session.currentTeam.id,customerId:input.customerId,opportunityId:opportunity.id,ownerUserId:session.user.id,title,dueAt:input.dueAt||dayOffset(1),status:'待处理',source:input.source??'手动',relatedId:input.relatedId,createdAt:now()};state.tasks.push(task);saveState(state);return{task}}
export function completeTask(session:SessionContext,taskId:string):{task?:SalesTask;error?:string}{const state=normalizeState();const task=state.tasks.find(t=>t.team_id===session.currentTeam.id&&t.id===taskId);if(!task)return{error:'任务不存在或不属于当前团队。'};if(task.status!=='已完成'){task.status='已完成';task.completedAt=now();saveState(state)}return{task}}

export function listQuotationSets(session:SessionContext):QuotationSet[]{normalizeState(session);return rawState().quotationSets.filter(s=>s.team_id===session.currentTeam.id)}
export function listQuotations(session:SessionContext):Quotation[]{return normalizeState(session).quotations.filter(q=>q.team_id===session.currentTeam.id).map(q=>({...q,lineItems:q.lineItems??[]})).sort((a,b)=>b.createdAt.localeCompare(a.createdAt))}
function normalizeItems(input:CreateQuotationInput):QuotationLineItem[]|undefined{const raw=input.lineItems?.length?input.lineItems:[{productName:input.productName??'',specification:input.specification,quantity:input.quantity,unitPrice:input.unitPrice,remark:input.remark}];if(raw.some(i=>!i.productName.trim()||money(i.quantity)<=0||money(i.unitPrice)<=0))return;return raw.map(i=>{const quantity=money(i.quantity),unitPrice=money(i.unitPrice);return{id:createId(),productName:i.productName.trim(),specification:i.specification?.trim()??'',quantity,unitPrice,subtotal:money(quantity*unitPrice),remark:i.remark?.trim()??''}})}
function applyTotals(q:Quotation){q.productAmount=money(q.lineItems.reduce((s,i)=>s+i.subtotal,0));q.totalAmount=money(q.productAmount+q.freightFee+q.installationFee+q.designFee-q.discountAmount)}
export function createQuotation(session:SessionContext,input:CreateQuotationInput):{quotation?:Quotation;task?:SalesTask;error?:string}{const error=customerError(session,input.customerId);if(error)return{error};const opportunity=resolveOpportunity(session,input.customerId,input.opportunityId);if(!opportunity)return{error:'项目不存在或不属于当前客户。'};const lineItems=normalizeItems(input);if(!lineItems)return{error:'每个报价产品都必须填写名称，且数量和单价必须大于 0。'};const state=normalizeState();const timestamp=now();const set:QuotationSet={id:createId(),team_id:session.currentTeam.id,customerId:input.customerId,opportunityId:opportunity.id,name:'报价',createdAt:timestamp};state.quotationSets.push(set);const quotation:Quotation={id:createId(),team_id:session.currentTeam.id,customerId:input.customerId,opportunityId:opportunity.id,quotationSetId:set.id,version:1,status:'草稿',productAmount:0,freightFee:money(input.freightFee),installationFee:money(input.installationFee),designFee:money(input.designFee),discountAmount:money(input.discountAmount),totalAmount:0,lineItems,feedback:'',createdAt:timestamp,updatedAt:timestamp};applyTotals(quotation);if(quotation.totalAmount<=0)return{error:'报价总额必须大于 0，折扣不能超过报价金额。'};state.quotations.push(quotation);saveState(state);return{quotation}}
export function updateQuotationDraft(session:SessionContext,id:string,changes:Partial<CreateQuotationInput>):{quotation?:Quotation;error?:string}{const state=normalizeState();const q=state.quotations.find(x=>x.team_id===session.currentTeam.id&&x.id===id);if(!q)return{error:'报价不存在或不属于当前团队。'};if(q.status!=='草稿')return{error:'只有草稿报价可以修改，请复制为新版本。'};if(changes.lineItems){const items=normalizeItems({customerId:q.customerId,lineItems:changes.lineItems});if(!items)return{error:'每个报价产品都必须填写名称，且数量和单价必须大于 0。'};q.lineItems=items}if(changes.freightFee!==undefined)q.freightFee=money(changes.freightFee);if(changes.installationFee!==undefined)q.installationFee=money(changes.installationFee);if(changes.designFee!==undefined)q.designFee=money(changes.designFee);if(changes.discountAmount!==undefined)q.discountAmount=money(changes.discountAmount);applyTotals(q);if(q.totalAmount<=0)return{error:'报价总额必须大于 0，折扣不能超过报价金额。'};q.updatedAt=now();saveState(state);return{quotation:q}}
export function copyQuotationVersion(session:SessionContext,id:string):{quotation?:Quotation;error?:string}{const state=normalizeState();const source=state.quotations.find(q=>q.team_id===session.currentTeam.id&&q.id===id);if(!source)return{error:'报价不存在或不属于当前团队。'};const timestamp=now();const q:Quotation={...source,id:createId(),version:Math.max(...state.quotations.filter(x=>x.quotationSetId===source.quotationSetId).map(x=>x.version))+1,status:'草稿',lineItems:source.lineItems.map(i=>({...i,id:createId()})),copiedFromId:source.id,createdAt:timestamp,updatedAt:timestamp,confirmedAt:undefined,sentAt:undefined,endedAt:undefined,statusReason:undefined};state.quotations.push(q);saveState(state);return{quotation:q}}
export function sendQuotation(session:SessionContext,id:string){const state=normalizeState();const q=state.quotations.find(x=>x.team_id===session.currentTeam.id&&x.id===id);if(!q)return{error:'报价不存在或不属于当前团队。'};if(q.status!=='草稿')return{error:'只有草稿报价可以发送。'};q.status='已发送';q.sentAt=now();q.updatedAt=q.sentAt;saveState(state);const task=createTask(session,{customerId:q.customerId,opportunityId:q.opportunityId,title:'确认客户是否接受报价，并记录异议或修改意见',dueAt:dayOffset(0),source:'报价生成',relatedId:q.id}).task;return{quotation:q,task}}
export function confirmQuotation(session:SessionContext,id:string){const state=normalizeState();const q=state.quotations.find(x=>x.team_id===session.currentTeam.id&&x.id===id);if(!q)return{error:'报价不存在或不属于当前团队。'};if(q.status!=='已发送')return{error:'只有已发送报价可以客户确认。'};const timestamp=now();for(const old of state.quotations.filter(x=>x.quotationSetId===q.quotationSetId&&x.status==='客户确认')){old.status='已被替代';old.endedAt=timestamp;old.statusReason=`由 V${q.version} 替代`}q.status='客户确认';q.confirmedAt=timestamp;q.updatedAt=timestamp;saveState(state);return{quotation:q}}
function endQuotation(session:SessionContext,id:string,status:'已作废'|'已过期',reason:string){const state=normalizeState();const q=state.quotations.find(x=>x.team_id===session.currentTeam.id&&x.id===id);if(!q)return{error:'报价不存在或不属于当前团队。'};if(!['草稿','已发送'].includes(q.status))return{error:'当前报价状态不能结束。'};q.status=status;q.endedAt=now();q.updatedAt=q.endedAt;q.statusReason=reason.trim();saveState(state);return{quotation:q}}
export const voidQuotation=(s:SessionContext,id:string,reason:string)=>endQuotation(s,id,'已作废',reason);
export const expireQuotation=(s:SessionContext,id:string,reason:string)=>endQuotation(s,id,'已过期',reason);
export function markQuotationConverted(session:SessionContext,id:string){const state=normalizeState();const q=state.quotations.find(x=>x.team_id===session.currentTeam.id&&x.id===id);if(!q)return{error:'报价不存在或不属于当前团队。'};if(q.status!=='客户确认')return{error:'只有客户确认报价可以转订单。'};q.status='已转订单';q.endedAt=now();q.updatedAt=q.endedAt;saveState(state);return{quotation:q}}
export function getMvpDashboard(session:SessionContext){const state=normalizeState();const tasks=state.tasks.filter(t=>t.team_id===session.currentTeam.id);const quotations=state.quotations.filter(q=>q.team_id===session.currentTeam.id);const raw=typeof localStorage==='undefined'?null:localStorage.getItem(ORDER_STORAGE_KEY);const orders=raw?(JSON.parse(raw).orders??[]).filter((o:{team_id:string})=>o.team_id===session.currentTeam.id):[];const nodes=orders.flatMap((o:{receivableNodes:Array<{plannedAmount:number;receivedAmount:number}>})=>o.receivableNodes);return{pendingTasks:tasks.filter(t=>t.status==='待处理').length,quotations:quotations.length,confirmedQuotations:quotations.filter(q=>q.status==='客户确认'||q.status==='已转订单').length,orders:orders.length,receivableAmount:money(nodes.reduce((s:number,n:{plannedAmount:number})=>s+n.plannedAmount,0)),receivedAmount:money(nodes.reduce((s:number,n:{receivedAmount:number})=>s+n.receivedAmount,0))}}
export function resetMvpFlowState():void{localStorage.removeItem(STORAGE_KEY)}
